### ISSUE TITLE
Use recommended code-block style

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#278]
## todos

* [x] Use recommended code block style:` .. code-block:: language`
* [x] Change the language, where it was not correct
* [x] Use captions where appropriate

https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Codeblocks.html

## details

Use recommended code block style:

`.. code-block:: <language>`

and not the short form.

`::`

Also, fix the correct language, where necessary. Sometimes, the wrong default language was used.

## Reasons for change

_Do not use shorthand `::`:_

> In the past a simplified shorthand directive was widely used: A sentence ending with two double colon ::, followed by a new line and > an indented block of code. This quick syntax has several drawbacks:

> It is confusing to developers who seldom contribute
> We cannot give a caption and state the file name where the code should go.
> The script language is only stated implicitly.
> Such code blocks cannot be easily copy-pasted to use them as a foundation for your own code blocks.

https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Codeblocks.html#outdated-code-block-formats

_Reason for captions:_

> For historic reasons the :caption: option is missing in many code blocks. Try to add them whenever you touch the RST files. Do not add new code blocks without a caption stating the file name. It is often very confusing for new developers where a certain code snippet should go. The recommended file name can help to clear this up.

https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Codeblocks.html#outdated-code-block-formats

This of course does not always make sense, e.g. for commands.

## Resources:

* code blocks: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Codeblocks.html
* available languages: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Codeblocks.html#writing-rest-codeblocks-available-lexers
