### ISSUE TITLE
Restructure guide 

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#78]
# Tasks

## structure

* [ ]  decide on general structure of guide
* [ ]  add chapters for contributing to docs and translation

In general: Name and structure the chapters as to what the person wants to do next. Focus on task, not tool. Use terminology that is common practices in contribution guides. 

Following things belong together and might be restructured:

* [ ] setup
  * Setting up your accounts
  * Setting up your environment

* [ ]  Submitting a patch
  * TYPO3 Contribution explained
  * Working with Gerrit
  * Fixing a bug

* [x]  restructure and rename some things in the appendix
  * [x]  titles should be self-explanatory
  * [x]  Things should not be hidden deep down in the directory structure
  

## possible subchapters

* [ ]  section: "Where to get help" in each chapter (info about slack channel and further reading)
* [x] use Quickstart at beginning, see #76   
* [ ]   section  "Contributors wanted" in each chapter with list of possible tasks (categorize by area and level of expertise) and  / links to issues + PR

## best practices

* [x]  all titles should be self-explanatory, dynamic and void subchapter headings should be avoided
* [ ]  Focus on the task, not the tool: What does the person reading want to do next?
* [ ] Structure each page / section which involves several steps into steps, see #77
* [x]  add information about what the guide is about on start page and beginning of subchapter
* [x] quicklinks. 
* [ ] Alternative to quicklinks: use tile images as quick links, see https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/22#issuecomment-398696052

# Inspiration

* [go contrib guidelines](https://golang.org/doc/contribute.html):
  * good: self-explanatory names for chapters, subsections
  * good: clear sitemap that fits on less than one page
  * good: numbering of steps
  * good: everything on one page, you don't have to click through pages with very little content
* ["How can I contribute" (Atom)](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute)
